services:
  frontend:
    container_name: workhair-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    image: workhair-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SITE_URL: https://workhairstyle.kxrn.online
      NEXT_PUBLIC_APP_URL: https://workhairstyle.kxrn.online
    networks:
      - main-network
